
enviroment: 'development'

discord:
  clientID: 'clientID'
  token: 'token'
  oauth: 'https://discordapp.com/oauth2/authorize?&client_id=<client_id>&scope=bot&permissions=66186303'

botAccess:
  - '203297462746611712'
  - '363845910477799448'